Add a Python example alongside the cURL example in the Aura API docs
neo4j/docs-aura pull request #324
Opened 2024-02-28 15:59 UTC by fiquick

Start with just an example on how to get the auth token in Python

2024-02-28 16:21 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-324.surge.sh

Updated pages:
- [Authentication](https://neo4j-docs-aura-324.surge.sh/aura/platform/api/authentication)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-02-28 16:28 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-324.surge.sh

Updated pages:
- [Authentication](https://neo4j-docs-aura-324.surge.sh/aura/platform/api/authentication)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-02-29 11:22 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-324.surge.sh

Updated pages:
- [Authentication](https://neo4j-docs-aura-324.surge.sh/aura/platform/api/authentication)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-02-29 11:59 UTC, nvitucci requested changes

2024-02-29 11:59 UTC, nvitucci commented on modules/ROOT/pages/platform/api/authentication.adoc
> +==== Code examples
```suggestion
==== Request examples 
```

2024-02-29 11:59 UTC, nvitucci commented on modules/ROOT/pages/platform/api/authentication.adoc
> +token = response.json()["access_token"]
```suggestion
print(response.json())
```

I would say let's just print the whole response in JSON format, so we are consistent with the output from cURL.

2024-03-04 09:58 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-324.surge.sh

Updated pages:
- [Authentication](https://neo4j-docs-aura-324.surge.sh/aura/platform/api/authentication)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-04 10:20 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-aura-324.surge.sh

Updated pages:
- [Authentication](https://neo4j-docs-aura-324.surge.sh/aura/platform/api/authentication)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-04 10:29 UTC, nvitucci approved these changes

2024-03-04 10:30 UTC, merged