first stab at copilots
neo4j/docs-aura pull request #510
Opened 2024-10-28 09:00 UTC by AlexicaWright

2024-10-29 18:00 UTC, gregoryking requested changes

2024-10-31 14:40 UTC, JeffG-N4j commented on modules/ROOT/pages/explore/explore-visual-tour/search-bar.adoc
I'd suggest removing the word 'yet' from "The co-pilot is an experimental feature and does not yet provide guaranteed accuracy."

2024-11-01 12:24 UTC, AlexicaWright commented on modules/ROOT/pages/visual-tour/index.adoc
> +On the organization level, you can also find a Settings menu where you can manage your organization's settings, provided that you are and organization admin.
Good eye!

2024-11-01 13:13 UTC, AlexicaWright commented on modules/ROOT/pages/explore/explore-visual-tour/search-bar.adoc
I was on the fence about that, but you are right, better leave it out.

2024-11-05 10:18 UTC, merged